# Replit Cloud Run Deployment Configuration
# Copy this content to your .replit file

[deployment]
run = ["node", "start.js"]
deploymentTarget = "cloudrun"
ignorePorts = false

[deployment.environment]
NODE_ENV = "production"
PORT = "8080"

[[deployment.ports]]
name = "main"
internalPort = 8080
externalPort = 80